### ISSUE TITLE
Problem with colcon build

### ISSUE THREAD

**Issue by pratipm** [aimechengineer/HomeBot-ROS2-Navigation#3]
Newbie to ROS.
Step 3 'colcon build' is failing with some error with xacro package.
Don't we have to run rosdep after Step 2 before running colcon build?

**Comment by aimechengineer** [comment]
Before running **colcon build**, follow the "Additional Steps for Gazebo Simulation." This should resolve the issue you're having with the xacro files. Also, ensure that you have installed the SLAM Toolbox and Nav2. If the issue persists, provide me with the error messages for further assistance.

**Comment by aimechengineer** [comment]
I’ve tested everything from scratch on three different laptops, and everything is working perfectly on my end
